%YAML:1.0
---
model_type: PINHOLE
camera_name: camera0
image_width: 640
image_height: 400
distortion_model: RADTAN
distortion_parameters:
  k1: 0
  k2: 0
  p1: 0
  p2: 0
projection_parameters:
  fx: 240.777
  fy: 240.506
  cx: 322.412
  cy: 196.373
