%YAML:1.0
---
model_type: PINHOLE
camera_name: camera1
image_width: 640
image_height: 400
distortion_model: RADTAN
distortion_parameters:
  k1: 0
  k2: 0
  p1: 0
  p2: 0
projection_parameters:
  fx: 240.396
  fy: 241.254
  cx: 339.421
  cy: 203.237
