%YAML:1.0
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2



imu_topic: "/imsee/imu"
image0_topic: "/imsee/image/rectified/left"
image1_topic: "/imsee/image/rectified/right"
output_path: "/home/l/output/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 640
image_height: 400
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [-0.998068, 0.0614698, -0.00900176, 0.06,
         -0.0614171, -0.998094, -0.00602787, 0.0,
         -0.00935513, -0.00546337, 0.999941, -0.00164,
         0.0, 0.0, 0.0, 1.0]



body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [-0.997821, 0.062463, -0.0212332, -0.0637139,
         -0.0622827, -0.998018, -0.00904748, -0.00775863,
         -0.0217563, -0.0077053, 0.999734, 0.00733252,
         0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 250           # max feature number in feature tracking
min_dist: 30            # min distance between two features
freq: 15              # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

acc_n: 0.009            # From IMU param: _sigma_a_c: 0.009
gyr_n: 0.12             # From IMU param: _sigma_g_c: 0.12
acc_w: 0.001            # From IMU param: _sigma_ba: 0.001
gyr_w: 0.1              # From IMU param: _sigma_bg: 0.1
g_norm: 9.802           # From IMU param: _g: 9.802

#unsynchronization parameters
estimate_td: 1                    # online estimate time offset between camera and imu
td: 0.0147                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 1        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/l/output" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

sift_flag: 0  #1为使用sift