%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam;
imu: 1
num_of_cam: 2

imu_topic: "/camera/imu"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "~/vins_sws/src/VINS-Fusion/vins_estimator/output"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

#body_T_cam0: !!opencv-matrix
#  rows: 4
#  cols: 4
#  dt: d
#  data: [ 1, 0, 0, -0.00552,
#          0, 1, 0, 0.0051,
#          0, 0, 1, 0.01174,
#          0, 0, 0, 1 ]

body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [ 9.9971228967285286e-01, 2.3020199838458086e-02, -6.7385663504431681e-03, -7.0604412328867314e-03,
          -2.2926371989380426e-02, 9.9964348808459291e-01, 1.3684962457852178e-02, 6.1524297983764692e-03,
          7.0511945418080283e-03, -1.3526534274001051e-02, 9.9988364999437207e-01, -1.0381520330196212e-03,
          0, 0, 0, 1 ]

body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [ 9.9993170151021016e-01, 5.4097123027909743e-03, -1.0359890332284747e-02, 5.5317759426769843e-02,
          -5.2517774779768838e-03, 9.9987050104199515e-01, 1.5211836817144815e-02, -5.0645813156189826e-03,
          1.0440840398059427e-02, -1.5156390032941872e-02, 9.9983062200202266e-01, 3.6154453280186474e-02,
          0, 0, 0, 1 ]
#body_T_cam1: !!opencv-matrix
#  rows: 4
#  cols: 4
#  dt: d
#  data: [ 1, 0, 0, 0.0446571,
#          0, 1, 0, 0.0051,
#          0, 0, 1, 0.01174,
#          0, 0, 0, 1 ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 250            # max feature number in feature tracking
min_dist: 25            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1
show_margin: 1
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.02         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0002         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.00002       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#unsynchronization parameters
estimate_td: 1
td: 0.00                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/l/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0

# 特征算法
sift_flag: 1          # 0=Shi-Tomasi, 1=SIFT-GPU